name: isl_kids_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.5
  flutter_otp_text_field: ^1.1.1
  line_awesome_flutter: ^2.0.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0
  table_calendar: ^3.0.9
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/otp_image.jpg
    - assets/images/dp.png
    - assets/images/two_peeps.png
    - assets/images/boy_1.png
    - assets/images/boy_2.png
    - assets/images/girl_1.png
    - assets/images/girl_2.png
    - assets/images/girl_3.png